spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://MyUser:1234@localhost:27017/myDB?authSource=admin

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

