spring:
  profiles:
    active: prod

  redis:
    host: localhost
    port: 6379
    password: 1234

  session:
    store-type: redis
    redis:
      flush-mode: on_save

server:
  port: 26000

  servlet:
    session:
      timeout: 600

